### ISSUE TITLE
Linux: 'thread main panicked' when putting a symlink on $PATH instead of the original wrapper script

### ISSUE THREAD

**Issue by axelknauf** [matthewwoodruff/sdoc#4]
Thanks for still providing this nice tool! <3

## Scenario

* System is a Ubuntu 20.04.3 LTS, 64bit Linux
* Installed per the instructions:

```
# Downloaded the Linux binary from Github releases page to ~/Downloads
cd
mkdir .sdoc
cd sdoc
cp ~/Downloads/sdoc .
./sdoc init
sdoc init
Setup a new CLI in "/home/user/.sdoc"? (y/n)
y
Enter your CLI name:
ds
Setup Complete
Execute ./bin/ds to begin. Even better, add '$(pwd)/bin' to your $PATH
cd ~/bin
# ~/bin is on my $PATH
ln -s ~/.sdoc/bin/ds
cd
ds
thread 'main' panicked at 'Failed to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

A backtrace shows:

```
thread 'main' panicked at 'Failed to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::result::unwrap_failed
   9: sdoc::config::file_config_source
  10: sdoc::config::Context::next
  11: sdoc::commands::node::execute
  12: sdoc::cli::run_cli
  13: sdoc::run
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  16: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  17: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  18: main
  19: __libc_start_main
  20: <unknown>
```

## Workaround

If I instead remove the symlink and put `~/.sdoc/bin/ds` on my $PATH, it works fine and shows the "hello world" example.

**Comment by matthewwoodruff** [comment]
This should now be fixed in https://github.com/matthewwoodruff/sdoc/releases/tag/v0.8.11 but the actual change is to the bootstrap script that wraps `sdoc` to determine the commands directory [here](https://github.com/matthewwoodruff/sdoc/commit/9d11bfb4c797f0f11fa9e879762c262faac0542c#diff-cadd09612a7d662d0ed12de2a0c70dc7afbea48e3aa5861398fea744dc49f476)

Previously it was
```
dir=$(cd $( dirname "${BASH_SOURCE[0]}" ) && cd .. && pwd )`
```

Now with the added `realpath`
```
dir=$(cd $( dirname $( realpath "${BASH_SOURCE[0]}" ) ) && cd .. && pwd )
```
Also added a test around the case 😄 Please try it out by either making the change manually or using the latest sdoc to create the bootstrap script and let me know how you get on.
